apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: assemblar
spec:
  ports:
    - port: 5432
  clusterIP: None
  selector:
    app: postgres
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres-svc-read
#   namespace: assemblar
# spec:
#   ports:
#     - port: 5432
#   selector:
#     app: postgres
#     role: replica