# Generated by Django 4.2.23 on 2025-07-29 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the instruction set', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InstructionStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('text', models.CharField(default='', max_length=1024)),
                ('initial_pos', models.JSONField(default=dict, help_text='Initial 3D position of the part in cartesian coordinates')),
                ('initial_rot', models.JSONField(default=dict, help_text='Initial 3D rotation of the part')),
                ('goal_pos', models.JSONField(default=dict, help_text='Goal 3D position of the part in cartesian coordinates')),
                ('goal_rot', models.JSONField(default=dict, help_text='Goal 3D rotation of the part')),
                ('scale', models.FloatField(default=1)),
                ('instruction_set', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.instructionset')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the organization', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file_bucket', models.CharField(help_text='S3 bucket where the file is located', max_length=255)),
                ('file_path', models.CharField(help_text='Path to the S3 model file', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InstructionStepMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('duration', models.FloatField()),
                ('instruction_step', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.instructionstep')),
            ],
        ),
        migrations.AddField(
            model_name='instructionstep',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.part'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.organization'),
        ),
    ]
