apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: assemblar-server-hpa
  namespace: assemblar
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: assemblar-server
  minReplicas: {{ .Values.assemblar_server.replicas }}
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
